### ISSUE TITLE
Penny will need some kind of time-based function that tells it to announce a prompt

### ISSUE THREAD

**Issue by adamsullovey** [the-heap/penny#12]
I want to try out [node-cron](https://github.com/kelektiv/node-cron) for this. I could set up a class or object that takes in a cron schedule and a prompt generator, and provides an event dispatcher or stream that emits drawing prompts for other objects to listen to. Those prompts could be sent to the chatroom by some other chunk of code.

**Comment by teesloane** [comment]
You got it! Keep us in the loop.

**Comment by adamsullovey** [comment]
My branch sent a message into the #draw_it channel on a timer. The code looks like this so far: https://github.com/the-heap/penny/compare/master...adamsullovey:scheduled-prompts?expand=1

I need to stop the timer if the chatroom disconnects. Edit: event names are here https://github.com/slackapi/node-slack-sdk/blob/master/lib/clients/events/client.js

Is this project going to use Jest for testing? I might add some tests for ScheduledPrompt to document usage.

**Comment by teesloane** [comment]
hey @adamsullovey,

Great work so far. I appreciate you adding a link to the chron docs in your code. Good documentation makes me happy.

As for testing: last project we used jest; yes. I like Jest, and I like testing. This project is going to be actively maintained for the month of July; so my stance on testing is that — everyone is welcome to write tests — however, it is important to note that the project can move fast and sometimes make tests become obsolete; or other developer do not update tests for _their_ next change.

In an ideal world we write tests, and good (but not too brittle ones at that. For now, I'd say, if you are up to keep contributing to the features / user stories of Penny that would be awesome so we can write tests when the actual development slows down towards the end of the month.

Now, on the other hand, If you want to write tests I certainly won't disregard them!

Thanks for contributing your time and code! Looking forward to your PR.
