### ISSUE TITLE
When I message Penny I should be able to know what its capabilities are.

### ISSUE THREAD

**Issue by teesloane** [the-heap/penny#4]
If you are interested in this feature; please comment and/or open an issue (for one of the checkboxes below). 

# Feature Checklist

- [ ] whenever someone messages Penny, it should respond with instructions on how to interact with penny.
- [ ] `@` mentioning Penny or DM'ing it, will provide the same response (for now).

**Comment by ericbastarache** [comment]
I'd love to work on this feature :)

**Comment by teesloane** [comment]
you got it !
