### ISSUE TITLE
Penny should provide a drawing prompt when asked

### ISSUE THREAD

**Issue by teesloane** [the-heap/penny#5]
**Read this to:**

- Work on a part of this feature.

**I expect you to know:**

- You have read our [roadmap](https://github.com/the-heap/penny/issues/1)
- You have read our [README](https://github.com/the-heap/penny/blob/master/README.md)
- You should probably [join our slack room](https://slackin-onxcmypksl.now.sh), since we're building a slack-bot after all.

---

# Feature Description

User's need to know what Penny is capable of doing, and how to interact with it. Because the features of Penny will continue to shape and change we'll have to continually come back to this issue and change things. 

# Goal

Whenever a user `@` messages Penny, or says anything to Penny in a DM, Penny should respond with a set of prompts we can say to it. 

# Issues

There will be more than one step to this issue. Below is a general outline that might have to happen. Pick an item below and make a new issue for it on Github and comment to let us know! Don't hesitate to work together as well.

- [x] Get penny in a slack room (I think this might be an admin problem for The Heap).
- [ ] Construct the basic replies that we can get Penny to say. For now, it should be very simply, such as "Hello, I'm Penny!"
- [ ] Make sure that Penny response in DM's the same as when you `@ mention` Penny
- [ ] Discuss the possible things that Penny should respond to.

**Comment by JelaniThompson** [comment]
I went to go add the basic replies (step 2 on the checklist) but the chunk of that seems to have been done already. I'll take a look at trying to add the bot responses in DMs now. Currently a DM message still triggers a message in the public channel (#draw_it) when it should be directly to the user in question if I'm not mistaken.

**Comment by teesloane** [comment]
@JelaniThompson Good call. We don't have any handler for when someone DM's Penny. Eventually we'd like to have a case where a user can DM their drawing upload and that needs to be handled in a DM rather than in the channel. Will review your [PR today](https://github.com/the-heap/penny/pull/22).
