### ISSUE TITLE
Penny should announce a drawing prompt for the whole team

### ISSUE THREAD

**Issue by teesloane** [the-heap/penny#6]
**Read this to:**

- Work on a part of this feature.

**I expect you to know:**

- You have read our [roadmap](https://github.com/the-heap/penny/issues/1)
- You have read our [README](https://github.com/the-heap/penny/blob/master/README.md)
- You should probably [join our slack room](https://slackin-onxcmypksl.now.sh), since we're building a slack-bot after all.

---

# Feature Description

Penny should, on a specified schedule, release  a drawing prompt for a specific time. For our first iteration, we will hard code in a time and day that Penny announced a prompt. 

# Issues

There will be more than one step to this issue. Below is a general outline that might have to happen. Pick an item below and make a new issue for it on Github and comment to let us know! Don't hesitate to work together as well.

- [ ] Penny will need some kind of time-based function (often referred to as a "chron job") that tells it to announce a prompt.
- [ ] Penny needs a database full of prompts. For this we can start by using a plain JSON file, and read / write to it using node. I do not think we will need a database.

**Comment by adamsullovey** [comment]
I'm interested in giving the cronjob stuff a try using [node-cron](https://github.com/kelektiv/node-cron). I could set up a class or object that takes in a cron schedule and a prompt generator, and provides an event dispatcher or stream that emits drawing prompts for other objects to listen to. Those prompts could be sent to the chatroom by some other chunk of code.

**Comment by teesloane** [comment]
That sounds great @adamsullovey . Can you open an issue and I will mark next to the checkbox for that task that you are working on it and I will link to the issue? 

For now, if you can get that working don't worry about what the actual prompts are... you can just use dummy text while we figure out the "database"
